#!/usr/bin/env bash
# Regenerates index.html by listing every briefs/YYYY-MM-DD.html file, newest first.
set -euo pipefail
cd "$(dirname "$0")"

items=""
# List dated brief files, sorted descending (newest first)
for f in $(ls -1 briefs/*.html 2>/dev/null | sort -r); do
  d="$(basename "$f" .html)"   # e.g. 2026-07-05
  # Human-friendly date (falls back to raw string if `date` can't parse)
  human="$(date -j -f "%Y-%m-%d" "$d" "+%A, %-d %B %Y" 2>/dev/null || echo "$d")"
  items="${items}    <li><a href=\"${f}\">${d}<span class=\"day\">${human}</span></a></li>\n"
done

if [ -z "$items" ]; then
  items="    <li><a href=\"#\">No briefs yet</a></li>\n"
fi

cat > index.html <<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Daily Tech Brief — Archive</title>
<link rel="stylesheet" href="assets/style.css">
</head>
<body>
<div class="wrap">
  <header class="page">
    <h1>📡 Daily Tech Brief</h1>
    <div class="date">AI · Cyber Security · Managed Services · ANZ — updated daily at 7am NZ</div>
  </header>
  <ul class="archive">
$(printf "%b" "$items")  </ul>
  <footer class="page">Generated by OpenClaw · newest brief first.</footer>
</div>
</body>
</html>
HTML

echo "index.html regenerated ($(ls -1 briefs/*.html 2>/dev/null | wc -l | tr -d ' ') briefs)"
